language: ruby
rvm:
- 2.3.1

branches:
  only:
    - master

before_install:
- git clone https://github.com/alan-yeh/CI.git
- cp CI/jekyll/* ./
- rm -rf CI
- rm example.travis.yml

install:
- bundle install

script: bundle exec rake site:deploy --quiet

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
env:
  global:
    # travis encrypt 'GH_TOKEN=YOUR_TOKEN'
    - secure: "GQABPltL5TfVc960SSSsaCow53pi945f1ol6wN6MV1CQKvuA8fAMT4TZgmVHjOWbcd2H/TYfPruAMLRV1aGTqmGFVR+ZvmoXS2QoaVZL6rmHJz/A7V1rrvhMuHEGRzHCattlNw68/tzxsT5K9TrZhC5XiYEjCUrhDXVacfCI6GVEz0VMs2Cl3UpQlzI4iTjy/bZZGvZtTvXQY4oz7KWQA20j4wAepuc3zx/xmEKuAJvbUtw3r7iO5MJFd32zeVIKolVI+Z3lowLi7yGdsS7gsnW/3S2OLoYoEqu/vnt7SvfMGrnBVVu37GZ13rKNIdcmr1ITeOyaX/ByxtefILJvKvMx8feLQwuoKHkeGQMQ+AAA+1t5waWWYUOw6uyWmqZ+xlgmM7G2IbMGAMgW01Duk//VWwdY6RrBnG3aMRdX/8yujh41rKV3CooNWDJJT0zaPtMOjdX1+/MUAUsXLQKfP3Jg9zocn584O+O44qSlK8zYvWT2/5O9N43GR9giKtXnwVYurk0yYMb8I6HL20CGGQM6sGdQQOa4B8hi0/4rvG42bmmOydSosf3c1xCrIhBsw3I0w53ae0kl1QMIJC6scF+OzUid6rJTN4p0DssNpGERiNrLuUYI4d7URp6u14/vAURQNX0hvXVX/SrYDHjFn8wv4/e4cH4yuT3aTlrD8A0="
    - GH_USER: alan-yeh
    #- GH_NAME: alan-yeh
    - GH_EMAIL: alan@yerl.cn